### ISSUE TITLE
No scroll bar in setting menu for certain tabs

### ISSUE THREAD

**Issue by konatachan** [RoliSoft/RS-TV-Show-Tracker#2]
Windows 7 x64, standart aero theme, problem persists in stable and nightly releases, 
In the settings tabs: General,Listing

**Comment by RoliSoft** [comment]
Although I couldn't reproduce, a similar graphical bug regarding inconsistent sizing was fixed by commit 54ce20e3b7299038874cf698bfb25ef2bfab9ed6.
